export enum ErrorCodes {
    // ================= AUTH =================
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    INVALID_PASSWORD = 'INVALID_PASSWORD',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    UNAUTHORIZED = 'UNAUTHORIZED',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    INVALID_TOKEN = 'INVALID_TOKEN',
    FORBIDDEN = 'FORBIDDEN',
    


    // ================= AUDIT LOG =================
    AUDITLOG_CREATE_FAILED = 'AUDITLOG_CREATE_FAILED',
    AUDITLOG_NOT_FOUND = 'AUDITLOG_NOT_FOUND',

    // ================= USER =================
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    USER_NOT_FOUND_DB = 'USER_NOT_FOUND_DB',
    USER_CREATE_FAILED = 'USER_CREATE_FAILED',
    USER_UPDATE_FAILED = 'USER_UPDATE_FAILED',
    USER_DELETE_FAILED = 'USER_DELETE_FAILED',
    USER_HAS_TASKS = 'USER_HAS_TASKS',

    // ================= TASK =================
    TASK_NOT_FOUND = 'TASK_NOT_FOUND',
    TASK_CREATE_FAILED = 'TASK_CREATE_FAILED',
    TASK_UPDATE_FAILED = 'TASK_UPDATE_FAILED',
    TASK_DELETE_FAILED = 'TASK_DELETE_FAILED',

    // ================= VALIDATION =================
    VALIDATION_ERROR = 'VALIDATION_ERROR',

    // ================= DATABASE =================
    UNIQUE_CONSTRAINT = 'UNIQUE_CONSTRAINT',
    FOREIGN_KEY_ERROR = 'FOREIGN_KEY_ERROR',
    DATABASE_ERROR = 'DATABASE_ERROR',

    // ================= GENERAL =================
    INTERNAL_ERROR = 'INTERNAL_ERROR',
}